services:
  - type: web
    name: ocr-service
    env: python
    buildCommand: |
      python -m venv venv
      . venv/bin/activate
      pip install -r requirements.txt
    startCommand: |
      . venv/bin/activate
      gunicorn wsgi:app
    plan: free
