services:
  - type: web
    name: ocr-service
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install gunicorn
      pip install -r requirements.txt
    startCommand: python -m gunicorn wsgi:app
    plan: free
